### ISSUE TITLE
已簽到會略過廣告雙倍巴幣

### ISSUE THREAD

**Issue by watain666** [tasi788/BahaAutoSign#2]
感謝 TDC 大的腳本，非常實用！

我在用的時候有發現一個問題，
如果在腳本自動執行的時間前登入過巴哈，
腳本執行後就不會去領廣告的雙倍巴幣了，
因爲這是流程設計上的問題，
所以我也不好意思直接改了發 PR，
先來問一下，謝謝。

**Comment by tasi788** [comment]
歡迎任何 PR 👀

**Comment by watain666** [comment]
我先讓他在我這測，跑個兩天沒問題就發 PR

**Comment by tasi788** [comment]
🐛 https://github.com/tasi788/BahaAutoSign/commit/48d5fefb4f8e1a938b6ed5037369718570728f4a

**Comment by watain666** [comment]
可以了 感謝🙏
